apiVersion: v1
kind: Secret
metadata:
  name: weather-db-secret
type: Opaque
stringData:
  db_server: "weatherdb.database.windows.net"
  db_name: "WeatherData"
  db_user: "<your-username>"
  db_password: "<your-password>"
